#:schema https://schemas.spinframework.dev/spin/manifest-v2/latest.json

spin_manifest_version = 2

[application]
name = "rust-n-body-spin"
version = "0.1.0"
authors = ["romeo"]
description = ""

[[trigger.command]]
component = "rust-n-body-spin"

[component.rust-n-body-spin]
source = "target/wasm32-wasip1/release/nbody.wasm"
allowed_outbound_hosts = []
[component.rust-n-body-spin.build]
command = "cargo build --target wasm32-wasip1 --release"
watch = ["src/**/*.rs", "Cargo.toml"]
